@extends('layouts.admin')

@section('content')
    <div class="w-full pt-20 px-10">
        <!-- Estadísticas Principales -->
        <div class="bg-gray-100 rounded-lg p-6 mb-6 shadow-lg">
            <h2 class="text-lg font-bold text-gray-800 mb-4">Estadísticas Principales</h2>
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                <!-- Ventas últimos 30 días -->
                <div class="p-4 bg-gray-200 rounded-xl">
                    <p class="text-gray-700 text-xl font-semibold">Ventas en los últimos 30 días</p>
                    <h3 class="text-3xl text-green-500 font-bold">${{ number_format($salesLast30Days, 2) }}</h3>
                </div>

                <!-- Ventas últimos 6 meses -->
                <div class="p-4 bg-gray-200 rounded-xl">
                    <p class="text-gray-700 text-xl font-semibold">Ventas en los últimos 6 meses</p>
                    <h3 class="text-3xl text-green-500 font-bold">${{ number_format($salesLast6Months, 2) }}</h3>
                </div>

                <!-- Productos vendidos en total -->
                <div class="p-4 bg-gray-200 rounded-xl">
                    <p class="text-gray-700 text-xl font-semibold">Productos vendidos en total</p>
                    <h3 class="text-3xl text-yellow-500 font-bold">{{ $totalProductsSold }}</h3>
                </div>

                <!-- Ganancias generadas -->
                <div class="p-4 bg-gray-200 rounded-xl">
                    <p class="text-gray-700 text-xl font-semibold">Ganancias generadas</p>
                    <h3 class="text-3xl text-blue-500 font-bold">${{ number_format($totalGanancias, 2) }}</h3>
                </div>

                <!-- Usuarios logueados -->
                <div class="p-4 bg-gray-200 rounded-xl">
                    <p class="text-gray-700 text-xl font-semibold">Usuarios logueados</p>
                    <h3 class="text-3xl text-purple-500 font-bold">{{ $loggedUsers }}</h3>
                </div>
            </div>
        </div>

        <!-- Gráfico de Categorías -->
        <div class="grid grid-cols-5 ">
            <div class="col-span-3">
                <div class="bg-white h-[50vh] flex justify-center p-6 rounded-xl border border-gray-200 mb-6 shadow-lg">
                    <div class="w-full">
                        <h2 class="text-lg font-bold text-gray-800 mb-4">Categorías</h2>
                        <canvas id="myChart"></canvas>
                    </div>
                </div>
            </div>
            <div class="col-span-2">
                <div class="bg-white p-6 rounded-xl border border-gray-200 mb-6 shadow-lg">
                    <h2 class="text-lg font-bold text-gray-800 mb-4">Ganancias por Categoría</h2>
                    <div class="grid grid-cols-2 gap-6">
                        @foreach ($earningsByCategory as $category)
                            <div class="bg-gray-50 p-4 rounded-xl border border-gray-200 shadow-sm">
                                <div class="flex items-center space-x-4">
                                    <div>
                                        <p class="text-gray-600 text-sm">{{ $categories[$category->category_id]->name }}</p>
                                        <h3 class="text-lg font-bold text-green-500">${{ number_format($category->total_earnings, 2) }}</h3>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
        

        

        <!-- Ganancias por Producto -->
        <div
            class='group/phyziro block items-center justify-center min-h-screen bg-[#0f0f0f] rounded-3xl pt-3 pb-20 px-10 border-2 border-gray-800 bg-gradient-to-t from-gray-900'>
            <h1 class='text-white text-5xl mt-7 mb-2 selected_font w-full h-auto text-center'>Earnings by Product</h1>
            <p class='text-gray-300 text-xs selected_font w-full h-auto text-center'>Track the earnings generated by each
                product.</p>

            <div class='flex relative place-content-center h-[50%] w-12/12 rounded-3xl p-3 m-7'>
                <div class='relative grid grid-cols-4 gap-6 z-10'>
                    @foreach ($earningsByProduct as $product)
                        <div class='flex group/bar place-items-center h-full w-auto'>
                            <center>
                                <div class='block h-96 w-auto'>
                                    <p class='block text-white text-center text-xs'>
                                        <span>{{ $product->name }}</span><br>
                                        <span
                                            class='font-extralight'>${{ number_format($product->total_earnings, 2) }}</span>
                                    </p>
                                    <div
                                        class='shadow-inner contrast-125 hue-rotate-180 saturate-100 flex align-center h-[{{ $highestEarning > 0 ? ($product->total_earnings / $highestEarning) * 100 : 0 }}%] w-[30px] bg-gray-900 rounded-3xl bg-gradient-to-t from-indigo-900 via-blue-700 to-blue-500 border border-indigo-900 shadow-md hover:shadow-blue-500/50 place-content-center'>
                                        <div
                                            class='shadow-inner shadow-md relative top-[0px] rounded-3xl h-auto m-[6px] w-[20px] bg-gradient-to-t from-indigo-800 via-blue-600 to-blue-700'>
                                        </div>
                                    </div>
                                </div>
                            </center>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Noto+Sans+Hatran&display=swap');
        .selected_font {
            font-family: "Inter", sans-serif;
        }
    </style>

    <script>
        const ctx = document.getElementById('myChart').getContext('2d');
        const topCategories = @json($topCategories);
        const categories = @json($categories);

        const labels = topCategories.map(category => categories[category.category_id]?.name || 'Unknown');
        const data = topCategories.map(category => category.total_sold);

        new Chart(ctx, {
            type: 'pie', // Cambiado de 'bar' a 'pie'
            data: {
                labels: labels,
                datasets: [{
                    label: 'Top Categories Sold',
                    data: data,
                    backgroundColor: [
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)',
                        'rgba(255, 99, 132, 0.2)'
                    ],
                    borderColor: [
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)',
                        'rgba(255, 99, 132, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        position: 'top',
                    },
                    tooltip: {
                        callbacks: {
                            label: function(context) {
                                const label = context.label || '';
                                const value = context.raw;
                                return `${label}: $${value.toFixed(2)}`;
                            }
                        }
                    }
                }
            }
        });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.6.2/dist/chart.min.js"></script>
@endsection
